Add feature to change lw and color
elide-b/starbars pull request #13
Opened 2024-10-07 15:59 UTC by erica-pathos

2024-10-09 14:10 UTC, elide-b requested changes
Hello! Thank you for your great contribution :)
I put some suggestions to have the style more in line with the current one. As soon as you accept them I can merge and release it ✨

2024-10-09 14:10 UTC, elide-b commented on starbars/__init__.py
> +    lw=1, c='k', **kwargs
```suggestion
    line_width=1, 
    color='k', 
    **kwargs
```

2024-10-09 14:10 UTC, elide-b commented on starbars/__init__.py
> +        ax.plot([c[0] for c in bar], [c[1] for c in bar], lw=lw, c=c, **kwargs)
```suggestion
        ax.plot([c[0] for c in bar], [c[1] for c in bar], lw=line_width, c=color, **kwargs)
```

2024-10-09 14:10 UTC, elide-b commented on starbars/__init__.py
> +                color=c,
```suggestion
                color=color,
```

2024-10-15 20:11 UTC, erica-pathos reviewed
Yea, it looks good, thanks.

2024-11-04 10:24 UTC, closed without merging